[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
phanuel = "Pha5A3BB4xKRZDs8ycvukFUagaKvk3AQBaH3J5qwAok"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
